### ISSUE TITLE
ERROR:root:file must have 'read' and 'readline' attributes

### ISSUE THREAD

**Issue by richard1225** [jinfagang/weibo_terminator_workflow#1]
When i am trying to run main.py, 
and login was successful,
but when it run to "getting content and comment..."
it throws an Error as follow:

**getting content and comment...
ERROR:root:file must have 'read' and 'readline' attributes
some error above not catch, return to dispatch center, resign for new account..**

**Comment by lucasjinreal** [comment]
This issue already be solved, just pull it.
