### ISSUE TITLE
A reminder for configuring accounts.py

### ISSUE THREAD

**Issue by quantnlp** [jinfagang/weibo_terminator_workflow#7]
Just a reminder:
When you add your own weibo id to the accouts.py to get your own cookies:
The "id" is your email or phone number, it is your weibo login, not the weibo ID: 273993327.

When you obtain weibos from different users, you put their id in the id file.

一个澄清：
在修改accounts.py里的id和密码设置时，id需要填入自己微博账号的登录名（一般是邮箱或者手机号），而不是微博分配给你账号的那一串数字id。

当抓取其他微博大V的微博时，需要输入微博大V账号的那一串数字或者字母，比如：273993327

**Comment by quantnlp** [comment]
Also, change the directory CORPUS_SAVE_DIR when error "settings/corpus not defined" appears.
For example  CORPUS_SAVE_DIR = 'D:/weibo_corpus/'

**Comment by lucasjinreal** [comment]
Right
